li=eval(input("enter the list you want "))
print("the list you have entered is")
print(li)
n=eval(input("enter the list you want to add in the previous list"))
print("the list you want to add is:")
print(n)
li.extend(n)
print(li)
s=sum(li)
print("the sum of the list is",s)
