num1=float(input("enter the first number you want to enter"))
num2=float(input("enter the second number you want to enter"))
num3=float(input("enter the third number you want to enter"))
print("largest number is",max(num1,num2,num3))
print("smallest number is",min(num1,num2,num3))
