# EXERSISE QUESTIONS OF THE CHAPTER RECURSION CLASS 12////

#Q..1..
# WAP THAT WILL FIQURE OUT WHETHER THE ENTERED NUMBER BY THE USER IS PRIME OR NOT...USING RECURSION.
n=int(input("ENTER THE NUMBER:  "))
global ct

    



# Q..2..IMPLEMENT A FUNCTION PRODUCT() TO MULTIPLY 2 NUMBERS RECURSIVELY USING + AND - OPERATORS ONLY....










#Q..3..HAILSTONE SEQUENCE GENERATOR,,,,(SEE QUESTION FROM SUMITA ARORA BOOK PG NO. 290)

    






#Q..4.. CREATE A FUNCTION FOR HAPPY NUMBER FOR CHECKING WHETHER THE ENTERED NUMBER IS HAPPY NUMBER OR NOT....


