print("write your school motto in the following inputs of word")
a=input("enter")
b=input("enter")
c=input("enter")
d=input("enter")
str1=" ".join([a,b,c,d])
print("enter the foundation date of your school")
dd=input("enter")
mm=input("enter")
yyyy=input("enter")
date="/".join([dd,mm,yyyy])
print("your school motto is",str1)
print("your school's foundation date is",date)
